const laptopProducts = [
  {
    id: 1,
    name: "Dell XPS 13",
    brand: "Dell",
    processor: "Intel Core i7",
    memory: "16GB RAM",
    storage: "512GB SSD",
    price: 1499.99,
    discountPrice: 1399.99,
    imageUrl: "url_to_product_image_1.jpg",
  },
  {
    id: 2,
    name: "MacBook Air",
    brand: "Apple",
    processor: "Apple M1",
    memory: "8GB RAM",
    storage: "256GB SSD",
    price: 999.99,
    discountPrice: null,
    imageUrl: "url_to_product_image_2.jpg",
  },
  {
    id: 3,
    name: "HP Spectre x360",
    brand: "HP",
    processor: "Intel Core i7",
    memory: "16GB RAM",
    storage: "512GB SSD",
    price: 1399.99,
    discountPrice: null,
    imageUrl: "url_to_product_image_3.jpg",
  },
  {
    id: 4,
    name: "Lenovo ThinkPad X1 Carbon",
    brand: "Lenovo",
    processor: "Intel Core i7",
    memory: "16GB RAM",
    storage: "512GB SSD",
    price: 1299.99,
    discountPrice: null,
    imageUrl: "url_to_product_image_4.jpg",
  },
  {
    id: 5,
    name: "Asus ROG Zephyrus G14",
    brand: "Asus",
    processor: "AMD Ryzen 9",
    memory: "32GB RAM",
    storage: "1TB SSD",
    price: 1699.99,
    discountPrice: 1599.99,
    imageUrl: "url_to_product_image_5.jpg",
  },
  {
    id: 6,
    name: "Acer Swift 5",
    brand: "Acer",
    processor: "Intel Core i5",
    memory: "8GB RAM",
    storage: "512GB SSD",
    price: 999.99,
    discountPrice: null,
    imageUrl: "url_to_product_image_6.jpg",
  },
  {
    id: 7,
    name: "Microsoft Surface Laptop 4",
    brand: "Microsoft",
    processor: "Intel Core i5",
    memory: "8GB RAM",
    storage: "256GB SSD",
    price: 1299.99,
    discountPrice: null,
    imageUrl: "url_to_product_image_7.jpg",
  },
  {
    id: 8,
    name: "Alienware m15",
    brand: "Dell",
    processor: "Intel Core i9",
    memory: "32GB RAM",
    storage: "1TB SSD",
    price: 2399.99,
    discountPrice: null,
    imageUrl: "url_to_product_image_8.jpg",
  },
  {
    id: 9,
    name: "LG Gram 17",
    brand: "LG",
    processor: "Intel Core i7",
    memory: "16GB RAM",
    storage: "512GB SSD",
    price: 1699.99,
    discountPrice: 1599.99,
    imageUrl: "url_to_product_image_9.jpg",
  },
  {
    id: 10,
    name: "Razer Blade 15",
    brand: "Razer",
    processor: "Intel Core i7",
    memory: "16GB RAM",
    storage: "512GB SSD",
    price: 1899.99,
    discountPrice: null,
    imageUrl: "url_to_product_image_10.jpg",
  },
  {
    id: 11,
    name: "HP Envy x360",
    brand: "HP",
    processor: "AMD Ryzen 7",
    memory: "16GB RAM",
    storage: "512GB SSD",
    price: 1299.99,
    discountPrice: null,
    imageUrl: "url_to_product_image_11.jpg",
  },
  {
    id: 12,
    name: "Google Pixelbook Go",
    brand: "Google",
    processor: "Intel Core i5",
    memory: "8GB RAM",
    storage: "128GB SSD",
    price: 899.99,
    discountPrice: null,
    imageUrl: "url_to_product_image_12.jpg",
  },
];

export default laptopProducts;
