import NavBar from "@/my-components/header/nav/NavBar";
import "./globals.css";
import { Poppins } from "next/font/google";

const poppins = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} m-0 overflow-y-auto`}>
        <NavBar />
        <main className="grid gap-20">{children}</main>
      </body>
    </html>
  );
}
